language: cpp

compiler:
  - clang
  - gcc

  addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - cmake
      - cmake-data
      - clang-3.7
      - g++-7

script:
- cmake -H. -B_build
- cmake --build _build
- echo "Hello world application testing is done"
- echo "Solver application testing is done"